//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentDto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttachmentDto()
        {
            this.FundingPackageDtoes = new HashSet<FundingPackageDto>();
            this.ProjectUpdateDtoes = new HashSet<ProjectUpdateDto>();
            this.ProjectCommentDtoes = new HashSet<ProjectCommentDto>();
        }
    
        public long AttachmentId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string FilePath { get; set; }
        public string Name { get; set; }
        public string HtmlCode { get; set; }
        public int OrderNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundingPackageDto> FundingPackageDtoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUpdateDto> ProjectUpdateDtoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCommentDto> ProjectCommentDtoes { get; set; }
    }
}
