//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundingPackageDto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FundingPackageDto()
        {
            this.UserFundingDTOes = new HashSet<UserFundingDTO>();
        }
    
        public long FundingPackageId { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> PledgeAmount { get; set; }
        public string Description { get; set; }
        public System.DateTime WhenDateTime { get; set; }
        public System.DateTime EstimatedDeliveryDate { get; set; }
        public long AttachmentId { get; set; }
        public long ProjectId { get; set; }
    
        public virtual AttachmentDto AttachmentDto { get; set; }
        public virtual ProjectDTO ProjectDTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFundingDTO> UserFundingDTOes { get; set; }
    }
}
