//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCommentDto
    {
        public long CommentId { get; set; }
        public string Name { get; set; }
        public long Id { get; set; }
        public System.DateTime WhenDateTime { get; set; }
        public string Description { get; set; }
        public long AttachmentId { get; set; }
        public long ProjectID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AttachmentDto AttachmentDto { get; set; }
        public virtual ProjectDTO ProjectDTO { get; set; }
    }
}
