//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUpdateDto
    {
        public long ProjectUpdateId { get; set; }
        public bool IsDeleted { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime WhenDateTime { get; set; }
        public long AttachmentId { get; set; }
        public long ProjectId { get; set; }
    
        public virtual AttachmentDto AttachmentDto { get; set; }
        public virtual ProjectDTO ProjectDTO { get; set; }
    }
}
