//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfundingPlatform.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFundingDTO
    {
        public long UserFundingId { get; set; }
        public string Username { get; set; }
        public System.DateTime WhenDateTime { get; set; }
        public decimal AmountPaid { get; set; }
        public string TransactionId { get; set; }
        public string AspNetUserId { get; set; }
        public long FundingPackageId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual FundingPackageDto FundingPackageDto { get; set; }
    }
}
